pipeline {
    agent  any
    stages {
        stage('Build') {
   
            steps {
                echo 'Building...'
                bat 'dotnet build' // °õ¦æ dotnet build
            }
        }
        stage('Test') {
            steps {
                echo 'Running Tests...'
                sh 'dotnet test' // °õ¦æ dotnet test
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
              
            }
        }
    }

} 