pipeline {
    agent any
    stages {
        stage('Build') {
        agent{
            docker
            {
                image 'mcr.microsoft.com/dotnet/sdk:8.0'
            }
        
        }
            steps {
                echo 'Building...'
                sh 'dotnet build' // 執行 dotnet build
            }
        }
        stage('Test') {
            steps {
                echo 'Running Tests...'
                sh 'dotnet test' // 執行 dotnet test
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                // 添加你的部署邏輯，例如將結果發佈到伺服器
            }
        }
    } // <- 確保這個大括號結束了 stages 區塊

} // <- 確保這個大括號結束了 pipeline 區塊